# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c2a4d84aed162b237558d50a0363fe7ac53a672cf9a2639298e037e79902ed70ff2f1d878e47420b14095e58cfc17a883685abf47d78dba6bfd2343fb92c276

test:
  secret_key_base: 117abbd690c88a9ae0ad4cc07e8d37d732beeb2961538788f4473670e6a1e5a2aec93214fae1518074b31313a8372aa0ff333311f7adeff4d616b0e36e66fff7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
